import express from "express";
import { createServer } from "http";
import { Server } from "socket.io";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import fs from "fs";
import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pdf = require("pdf-parse");
import mammoth from "mammoth";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const httpServer = createServer(app);
  const io = new Server(httpServer, {
    cors: {
      origin: "*",
    },
  });

  const PORT = 3000;

  app.use(express.json({ limit: "50mb" }));

  // API Routes
  app.post("/api/extract-text", async (req, res) => {
    try {
      const { fileData, fileName, mimeType } = req.body;
      if (!fileData) return res.status(400).json({ error: "No file data provided" });
      const buffer = Buffer.from(fileData.split(",")[1], "base64");
      
      let text = "";
      if (mimeType === "application/pdf") {
        const data = await pdf(buffer);
        text = data.text;
      } else if (mimeType === "application/vnd.openxmlformats-officedocument.wordprocessingml.document") {
        const result = await mammoth.extractRawText({ buffer });
        text = result.value;
      } else if (mimeType.startsWith("text/")) {
        text = buffer.toString("utf-8");
      } else {
        return res.status(400).json({ error: `Unsupported file type: ${mimeType}` });
      }

      res.json({ text: text.trim() });
    } catch (error: any) {
      console.error("Extraction error:", error);
      res.status(500).json({ error: "Failed to extract text from file" });
    }
  });

  // Socket.io for Arena
  const players = new Map();
  const matchmakingQueue: any[] = [];
  const activeBattles = new Map();

  app.post("/api/battle/start", async (req, res) => {
    const { players: battlePlayers, context } = req.body;
    try {
      // Questions will be generated by the lobby creator/server 
      // but in this simplified version we assume questions are requested per battle
      res.json({ battleId: `battle-${Date.now()}` });
    } catch (error) {
      res.status(500).json({ error: "Failed to start battle" });
    }
  });

  io.on("connection", (socket) => {
    console.log("User connected:", socket.id);

    socket.on("join-lobby", (username) => {
      players.set(socket.id, { id: socket.id, username, score: 0, status: "idle" });
      io.emit("players-update", Array.from(players.values()));
    });

    socket.on("find-match", () => {
      const player = players.get(socket.id);
      if (!player || player.status !== "idle") return;

      player.status = "matching";
      matchmakingQueue.push(socket.id);

      if (matchmakingQueue.length >= 2) {
        const p1Id = matchmakingQueue.shift();
        const p2Id = matchmakingQueue.shift();
        const p1 = players.get(p1Id);
        const p2 = players.get(p2Id);

        if (p1 && p2) {
          const battleId = `battle-${p1Id}-${p2Id}`;
          p1.status = "in-battle";
          p2.status = "in-battle";
          
          activeBattles.set(battleId, {
            id: battleId,
            players: [p1, p2],
            scores: { [p1Id]: 0, [p2Id]: 0 },
            finished: { [p1Id]: false, [p2Id]: false }
          });

          io.to(p1Id).emit("match-found", { battleId, opponent: p2 });
          io.to(p2Id).emit("match-found", { battleId, opponent: p1 });
        }
      }
      io.emit("players-update", Array.from(players.values()));
    });

    socket.on("cancel-match", () => {
      const index = matchmakingQueue.indexOf(socket.id);
      if (index !== -1) matchmakingQueue.splice(index, 1);
      const player = players.get(socket.id);
      if (player) player.status = "idle";
      io.emit("players-update", Array.from(players.values()));
    });

    socket.on("submit-battle-answer", ({ battleId, correct, timeLeft }) => {
      const battle = activeBattles.get(battleId);
      if (battle) {
        if (correct) {
          const points = 10 + timeLeft;
          battle.scores[socket.id] += points;
        }
        io.to(battle.players[0].id).to(battle.players[1].id).emit("battle-update", { scores: battle.scores });
      }
    });

    socket.on("finish-battle", ({ battleId }) => {
      const battle = activeBattles.get(battleId);
      if (battle) {
        battle.finished[socket.id] = true;
        if (Object.values(battle.finished).every(v => v)) {
          io.to(battle.players[0].id).to(battle.players[1].id).emit("battle-finished", { scores: battle.scores });
          battle.players.forEach((p: any) => {
            const player = players.get(p.id);
            if (player) player.status = "idle";
          });
          activeBattles.delete(battleId);
          io.emit("players-update", Array.from(players.values()));
        }
      }
    });

    socket.on("disconnect", () => {
      const index = matchmakingQueue.indexOf(socket.id);
      if (index !== -1) matchmakingQueue.splice(index, 1);
      players.delete(socket.id);
      io.emit("players-update", Array.from(players.values()));
    });
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  httpServer.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
